version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      PORT: '8000'
      HOST: '0.0.0.0'
    ports:
      - 8000:8000
    stdin_open: true
    restart: always
    command: ["deno", "run", "--allow-net", "--allow-read", "src/endpoint/server.ts"]
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432
    volumes:
      - "db:/var/lib/postgresql/data"
    command: >
      -c log_statement=all

volumes:
  db: {}